/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServiceInventoryIndexRouteImport } from './routes/_authenticated/service-inventory/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedUsersRolesRouteImport } from './routes/_authenticated/users/roles'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedInventoryReqIndexRouteImport } from './routes/_authenticated/inventory/req/index'
import { Route as AuthenticatedInventoryReptIndexRouteImport } from './routes/_authenticated/inventory/rept/index'
import { Route as AuthenticatedInventoryProgIndexRouteImport } from './routes/_authenticated/inventory/prog/index'
import { Route as AuthenticatedInventoryApprIndexRouteImport } from './routes/_authenticated/inventory/appr/index'
import { Route as AuthenticatedInventoryAdminIndexRouteImport } from './routes/_authenticated/inventory/admin/index'

const AuthenticatedTransactionsLazyRouteImport = createFileRoute(
  '/_authenticated/transactions',
)()
const AuthenticatedTeamLazyRouteImport = createFileRoute(
  '/_authenticated/team',
)()
const AuthenticatedServicesLazyRouteImport = createFileRoute(
  '/_authenticated/services',
)()
const AuthenticatedCustomersLazyRouteImport = createFileRoute(
  '/_authenticated/customers',
)()
const AuthenticatedOperationalServiceLazyRouteImport = createFileRoute(
  '/_authenticated/operational/service',
)()
const AuthenticatedOperationalSchedulingLazyRouteImport = createFileRoute(
  '/_authenticated/operational/scheduling',
)()
const AuthenticatedOperationalPeopleLazyRouteImport = createFileRoute(
  '/_authenticated/operational/people',
)()
const AuthenticatedControllerTaxLazyRouteImport = createFileRoute(
  '/_authenticated/controller/tax',
)()
const AuthenticatedControllerLedgerLazyRouteImport = createFileRoute(
  '/_authenticated/controller/ledger',
)()
const AuthenticatedControllerCashLazyRouteImport = createFileRoute(
  '/_authenticated/controller/cash',
)()
const AuthenticatedControllerBankLazyRouteImport = createFileRoute(
  '/_authenticated/controller/bank',
)()
const AuthenticatedControllerAttendanceLazyRouteImport = createFileRoute(
  '/_authenticated/controller/attendance',
)()
const AuthenticatedControllerAdminLazyRouteImport = createFileRoute(
  '/_authenticated/controller/admin',
)()

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsLazyRoute =
  AuthenticatedTransactionsLazyRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/transactions.lazy').then((d) => d.Route),
  )
const AuthenticatedTeamLazyRoute = AuthenticatedTeamLazyRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/team.lazy').then((d) => d.Route),
)
const AuthenticatedServicesLazyRoute =
  AuthenticatedServicesLazyRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/services.lazy').then((d) => d.Route),
  )
const AuthenticatedCustomersLazyRoute =
  AuthenticatedCustomersLazyRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customers.lazy').then((d) => d.Route),
  )
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceInventoryIndexRoute =
  AuthenticatedServiceInventoryIndexRouteImport.update({
    id: '/service-inventory/',
    path: '/service-inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationalServiceLazyRoute =
  AuthenticatedOperationalServiceLazyRouteImport.update({
    id: '/operational/service',
    path: '/operational/service',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/operational/service.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedOperationalSchedulingLazyRoute =
  AuthenticatedOperationalSchedulingLazyRouteImport.update({
    id: '/operational/scheduling',
    path: '/operational/scheduling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/operational/scheduling.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedOperationalPeopleLazyRoute =
  AuthenticatedOperationalPeopleLazyRouteImport.update({
    id: '/operational/people',
    path: '/operational/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/operational/people.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedControllerTaxLazyRoute =
  AuthenticatedControllerTaxLazyRouteImport.update({
    id: '/controller/tax',
    path: '/controller/tax',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/controller/tax.lazy').then((d) => d.Route),
  )
const AuthenticatedControllerLedgerLazyRoute =
  AuthenticatedControllerLedgerLazyRouteImport.update({
    id: '/controller/ledger',
    path: '/controller/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/controller/ledger.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedControllerCashLazyRoute =
  AuthenticatedControllerCashLazyRouteImport.update({
    id: '/controller/cash',
    path: '/controller/cash',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/controller/cash.lazy').then((d) => d.Route),
  )
const AuthenticatedControllerBankLazyRoute =
  AuthenticatedControllerBankLazyRouteImport.update({
    id: '/controller/bank',
    path: '/controller/bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/controller/bank.lazy').then((d) => d.Route),
  )
const AuthenticatedControllerAttendanceLazyRoute =
  AuthenticatedControllerAttendanceLazyRouteImport.update({
    id: '/controller/attendance',
    path: '/controller/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/controller/attendance.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedControllerAdminLazyRoute =
  AuthenticatedControllerAdminLazyRouteImport.update({
    id: '/controller/admin',
    path: '/controller/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/controller/admin.lazy').then(
      (d) => d.Route,
    ),
  )
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedUsersRolesRoute = AuthenticatedUsersRolesRouteImport.update({
  id: '/users/roles',
  path: '/users/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/settings/display',
    path: '/settings/display',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryReqIndexRoute =
  AuthenticatedInventoryReqIndexRouteImport.update({
    id: '/inventory/req/',
    path: '/inventory/req/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryReptIndexRoute =
  AuthenticatedInventoryReptIndexRouteImport.update({
    id: '/inventory/rept/',
    path: '/inventory/rept/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryProgIndexRoute =
  AuthenticatedInventoryProgIndexRouteImport.update({
    id: '/inventory/prog/',
    path: '/inventory/prog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryApprIndexRoute =
  AuthenticatedInventoryApprIndexRouteImport.update({
    id: '/inventory/appr/',
    path: '/inventory/appr/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryAdminIndexRoute =
  AuthenticatedInventoryAdminIndexRouteImport.update({
    id: '/inventory/admin/',
    path: '/inventory/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/customers': typeof AuthenticatedCustomersLazyRoute
  '/services': typeof AuthenticatedServicesLazyRoute
  '/team': typeof AuthenticatedTeamLazyRoute
  '/transactions': typeof AuthenticatedTransactionsLazyRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/roles': typeof AuthenticatedUsersRolesRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/controller/admin': typeof AuthenticatedControllerAdminLazyRoute
  '/controller/attendance': typeof AuthenticatedControllerAttendanceLazyRoute
  '/controller/bank': typeof AuthenticatedControllerBankLazyRoute
  '/controller/cash': typeof AuthenticatedControllerCashLazyRoute
  '/controller/ledger': typeof AuthenticatedControllerLedgerLazyRoute
  '/controller/tax': typeof AuthenticatedControllerTaxLazyRoute
  '/operational/people': typeof AuthenticatedOperationalPeopleLazyRoute
  '/operational/scheduling': typeof AuthenticatedOperationalSchedulingLazyRoute
  '/operational/service': typeof AuthenticatedOperationalServiceLazyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/service-inventory/': typeof AuthenticatedServiceInventoryIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/inventory/admin/': typeof AuthenticatedInventoryAdminIndexRoute
  '/inventory/appr/': typeof AuthenticatedInventoryApprIndexRoute
  '/inventory/prog/': typeof AuthenticatedInventoryProgIndexRoute
  '/inventory/rept/': typeof AuthenticatedInventoryReptIndexRoute
  '/inventory/req/': typeof AuthenticatedInventoryReqIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/customers': typeof AuthenticatedCustomersLazyRoute
  '/services': typeof AuthenticatedServicesLazyRoute
  '/team': typeof AuthenticatedTeamLazyRoute
  '/transactions': typeof AuthenticatedTransactionsLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/roles': typeof AuthenticatedUsersRolesRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/controller/admin': typeof AuthenticatedControllerAdminLazyRoute
  '/controller/attendance': typeof AuthenticatedControllerAttendanceLazyRoute
  '/controller/bank': typeof AuthenticatedControllerBankLazyRoute
  '/controller/cash': typeof AuthenticatedControllerCashLazyRoute
  '/controller/ledger': typeof AuthenticatedControllerLedgerLazyRoute
  '/controller/tax': typeof AuthenticatedControllerTaxLazyRoute
  '/operational/people': typeof AuthenticatedOperationalPeopleLazyRoute
  '/operational/scheduling': typeof AuthenticatedOperationalSchedulingLazyRoute
  '/operational/service': typeof AuthenticatedOperationalServiceLazyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/service-inventory': typeof AuthenticatedServiceInventoryIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/inventory/admin': typeof AuthenticatedInventoryAdminIndexRoute
  '/inventory/appr': typeof AuthenticatedInventoryApprIndexRoute
  '/inventory/prog': typeof AuthenticatedInventoryProgIndexRoute
  '/inventory/rept': typeof AuthenticatedInventoryReptIndexRoute
  '/inventory/req': typeof AuthenticatedInventoryReqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/customers': typeof AuthenticatedCustomersLazyRoute
  '/_authenticated/services': typeof AuthenticatedServicesLazyRoute
  '/_authenticated/team': typeof AuthenticatedTeamLazyRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/users/roles': typeof AuthenticatedUsersRolesRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/controller/admin': typeof AuthenticatedControllerAdminLazyRoute
  '/_authenticated/controller/attendance': typeof AuthenticatedControllerAttendanceLazyRoute
  '/_authenticated/controller/bank': typeof AuthenticatedControllerBankLazyRoute
  '/_authenticated/controller/cash': typeof AuthenticatedControllerCashLazyRoute
  '/_authenticated/controller/ledger': typeof AuthenticatedControllerLedgerLazyRoute
  '/_authenticated/controller/tax': typeof AuthenticatedControllerTaxLazyRoute
  '/_authenticated/operational/people': typeof AuthenticatedOperationalPeopleLazyRoute
  '/_authenticated/operational/scheduling': typeof AuthenticatedOperationalSchedulingLazyRoute
  '/_authenticated/operational/service': typeof AuthenticatedOperationalServiceLazyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/service-inventory/': typeof AuthenticatedServiceInventoryIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/inventory/admin/': typeof AuthenticatedInventoryAdminIndexRoute
  '/_authenticated/inventory/appr/': typeof AuthenticatedInventoryApprIndexRoute
  '/_authenticated/inventory/prog/': typeof AuthenticatedInventoryProgIndexRoute
  '/_authenticated/inventory/rept/': typeof AuthenticatedInventoryReptIndexRoute
  '/_authenticated/inventory/req/': typeof AuthenticatedInventoryReqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/customers'
    | '/services'
    | '/team'
    | '/transactions'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/roles'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/controller/admin'
    | '/controller/attendance'
    | '/controller/bank'
    | '/controller/cash'
    | '/controller/ledger'
    | '/controller/tax'
    | '/operational/people'
    | '/operational/scheduling'
    | '/operational/service'
    | '/admin/'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/inventory/'
    | '/service-inventory/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/inventory/admin/'
    | '/inventory/appr/'
    | '/inventory/prog/'
    | '/inventory/rept/'
    | '/inventory/req/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/customers'
    | '/services'
    | '/team'
    | '/transactions'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/roles'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/controller/admin'
    | '/controller/attendance'
    | '/controller/bank'
    | '/controller/cash'
    | '/controller/ledger'
    | '/controller/tax'
    | '/operational/people'
    | '/operational/scheduling'
    | '/operational/service'
    | '/admin'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/inventory'
    | '/service-inventory'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/inventory/admin'
    | '/inventory/appr'
    | '/inventory/prog'
    | '/inventory/rept'
    | '/inventory/req'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/customers'
    | '/_authenticated/services'
    | '/_authenticated/team'
    | '/_authenticated/transactions'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/users/roles'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/controller/admin'
    | '/_authenticated/controller/attendance'
    | '/_authenticated/controller/bank'
    | '/_authenticated/controller/cash'
    | '/_authenticated/controller/ledger'
    | '/_authenticated/controller/tax'
    | '/_authenticated/operational/people'
    | '/_authenticated/operational/scheduling'
    | '/_authenticated/operational/service'
    | '/_authenticated/admin/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/inventory/'
    | '/_authenticated/service-inventory/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/inventory/admin/'
    | '/_authenticated/inventory/appr/'
    | '/_authenticated/inventory/prog/'
    | '/_authenticated/inventory/rept/'
    | '/_authenticated/inventory/req/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-inventory/': {
      id: '/_authenticated/service-inventory/'
      path: '/service-inventory'
      fullPath: '/service-inventory/'
      preLoaderRoute: typeof AuthenticatedServiceInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operational/service': {
      id: '/_authenticated/operational/service'
      path: '/operational/service'
      fullPath: '/operational/service'
      preLoaderRoute: typeof AuthenticatedOperationalServiceLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operational/scheduling': {
      id: '/_authenticated/operational/scheduling'
      path: '/operational/scheduling'
      fullPath: '/operational/scheduling'
      preLoaderRoute: typeof AuthenticatedOperationalSchedulingLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operational/people': {
      id: '/_authenticated/operational/people'
      path: '/operational/people'
      fullPath: '/operational/people'
      preLoaderRoute: typeof AuthenticatedOperationalPeopleLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/tax': {
      id: '/_authenticated/controller/tax'
      path: '/controller/tax'
      fullPath: '/controller/tax'
      preLoaderRoute: typeof AuthenticatedControllerTaxLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/ledger': {
      id: '/_authenticated/controller/ledger'
      path: '/controller/ledger'
      fullPath: '/controller/ledger'
      preLoaderRoute: typeof AuthenticatedControllerLedgerLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/cash': {
      id: '/_authenticated/controller/cash'
      path: '/controller/cash'
      fullPath: '/controller/cash'
      preLoaderRoute: typeof AuthenticatedControllerCashLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/bank': {
      id: '/_authenticated/controller/bank'
      path: '/controller/bank'
      fullPath: '/controller/bank'
      preLoaderRoute: typeof AuthenticatedControllerBankLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/attendance': {
      id: '/_authenticated/controller/attendance'
      path: '/controller/attendance'
      fullPath: '/controller/attendance'
      preLoaderRoute: typeof AuthenticatedControllerAttendanceLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/admin': {
      id: '/_authenticated/controller/admin'
      path: '/controller/admin'
      fullPath: '/controller/admin'
      preLoaderRoute: typeof AuthenticatedControllerAdminLazyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/users/roles': {
      id: '/_authenticated/users/roles'
      path: '/users/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof AuthenticatedUsersRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/req/': {
      id: '/_authenticated/inventory/req/'
      path: '/inventory/req'
      fullPath: '/inventory/req/'
      preLoaderRoute: typeof AuthenticatedInventoryReqIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/rept/': {
      id: '/_authenticated/inventory/rept/'
      path: '/inventory/rept'
      fullPath: '/inventory/rept/'
      preLoaderRoute: typeof AuthenticatedInventoryReptIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/prog/': {
      id: '/_authenticated/inventory/prog/'
      path: '/inventory/prog'
      fullPath: '/inventory/prog/'
      preLoaderRoute: typeof AuthenticatedInventoryProgIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/appr/': {
      id: '/_authenticated/inventory/appr/'
      path: '/inventory/appr'
      fullPath: '/inventory/appr/'
      preLoaderRoute: typeof AuthenticatedInventoryApprIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/admin/': {
      id: '/_authenticated/inventory/admin/'
      path: '/inventory/admin'
      fullPath: '/inventory/admin/'
      preLoaderRoute: typeof AuthenticatedInventoryAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersLazyRoute: typeof AuthenticatedCustomersLazyRoute
  AuthenticatedServicesLazyRoute: typeof AuthenticatedServicesLazyRoute
  AuthenticatedTeamLazyRoute: typeof AuthenticatedTeamLazyRoute
  AuthenticatedTransactionsLazyRoute: typeof AuthenticatedTransactionsLazyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedUsersRolesRoute: typeof AuthenticatedUsersRolesRoute
  AuthenticatedControllerAdminLazyRoute: typeof AuthenticatedControllerAdminLazyRoute
  AuthenticatedControllerAttendanceLazyRoute: typeof AuthenticatedControllerAttendanceLazyRoute
  AuthenticatedControllerBankLazyRoute: typeof AuthenticatedControllerBankLazyRoute
  AuthenticatedControllerCashLazyRoute: typeof AuthenticatedControllerCashLazyRoute
  AuthenticatedControllerLedgerLazyRoute: typeof AuthenticatedControllerLedgerLazyRoute
  AuthenticatedControllerTaxLazyRoute: typeof AuthenticatedControllerTaxLazyRoute
  AuthenticatedOperationalPeopleLazyRoute: typeof AuthenticatedOperationalPeopleLazyRoute
  AuthenticatedOperationalSchedulingLazyRoute: typeof AuthenticatedOperationalSchedulingLazyRoute
  AuthenticatedOperationalServiceLazyRoute: typeof AuthenticatedOperationalServiceLazyRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedServiceInventoryIndexRoute: typeof AuthenticatedServiceInventoryIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedInventoryAdminIndexRoute: typeof AuthenticatedInventoryAdminIndexRoute
  AuthenticatedInventoryApprIndexRoute: typeof AuthenticatedInventoryApprIndexRoute
  AuthenticatedInventoryProgIndexRoute: typeof AuthenticatedInventoryProgIndexRoute
  AuthenticatedInventoryReptIndexRoute: typeof AuthenticatedInventoryReptIndexRoute
  AuthenticatedInventoryReqIndexRoute: typeof AuthenticatedInventoryReqIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersLazyRoute: AuthenticatedCustomersLazyRoute,
  AuthenticatedServicesLazyRoute: AuthenticatedServicesLazyRoute,
  AuthenticatedTeamLazyRoute: AuthenticatedTeamLazyRoute,
  AuthenticatedTransactionsLazyRoute: AuthenticatedTransactionsLazyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedUsersRolesRoute: AuthenticatedUsersRolesRoute,
  AuthenticatedControllerAdminLazyRoute: AuthenticatedControllerAdminLazyRoute,
  AuthenticatedControllerAttendanceLazyRoute:
    AuthenticatedControllerAttendanceLazyRoute,
  AuthenticatedControllerBankLazyRoute: AuthenticatedControllerBankLazyRoute,
  AuthenticatedControllerCashLazyRoute: AuthenticatedControllerCashLazyRoute,
  AuthenticatedControllerLedgerLazyRoute:
    AuthenticatedControllerLedgerLazyRoute,
  AuthenticatedControllerTaxLazyRoute: AuthenticatedControllerTaxLazyRoute,
  AuthenticatedOperationalPeopleLazyRoute:
    AuthenticatedOperationalPeopleLazyRoute,
  AuthenticatedOperationalSchedulingLazyRoute:
    AuthenticatedOperationalSchedulingLazyRoute,
  AuthenticatedOperationalServiceLazyRoute:
    AuthenticatedOperationalServiceLazyRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedServiceInventoryIndexRoute:
    AuthenticatedServiceInventoryIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedInventoryAdminIndexRoute: AuthenticatedInventoryAdminIndexRoute,
  AuthenticatedInventoryApprIndexRoute: AuthenticatedInventoryApprIndexRoute,
  AuthenticatedInventoryProgIndexRoute: AuthenticatedInventoryProgIndexRoute,
  AuthenticatedInventoryReptIndexRoute: AuthenticatedInventoryReptIndexRoute,
  AuthenticatedInventoryReqIndexRoute: AuthenticatedInventoryReqIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
